language: node_js
node_js:
  - stable

script:
  - make install
  - make build
  - make test
  - make lint

deploy:
  provider: heroku
  app: safe-forest-48671
  api_key: "$HEROKU_ACCESS_TOKEN"
  skip_cleanup: true
  on:
    branch: release