language: node_js
node_js:
  - stable

script:
  - make install
  - make test
  - make lint

deploy:
  provider: heroku
  app: safe-forest-48671
  api_key: "$HEROKU_ACCESS_TOKEN"
  on:
    branch: release